### ISSUE TITLE
Simultaneous wheel lerping

### ISSUE THREAD

**Issue by naterpotatoers** [SJSURoboticsTeam/urc-central-2021#171]
Original lerp mode was implemented within wheel class which meant rover would accelerate each wheel one by one. This would lead to future problems for the rover and is not correct way to implement lerp for our project.

Recreate lerp procedure from within drive_system file. End result should be a lerp handler that will quickly call each rover leg and set all the hub speeds at nearly the same time.

This should be non-blocking. Will require the use of some sort of timer

i.e.
```c++ 
// Main control loop
while()
{
   Action1();
  Action2();
   Action3();
  left_wheel.MoveWheel();
  right_wheel...
}

// rough example
MoveWheel(rpm target_speed) 
{
  if(!(Uptime() % 10)) // ~at least 10ms has passed, gives time for motor to move
  {
    motor_speed = std::lerp(previous_speed, target_speed, 0.01);
    motor(motor_speed);
    previous_speed = motor_speed;
  }
}

**Comment by naterpotatoers** [comment]
Please refer to #153 for additional lerp information

**Comment by naterpotatoers** [comment]
May want to investigate #181 since this may be easier solution since lerp could have unforeseen consequences (thread lock, additional testing...)

**Comment by kammce** [comment]
Just to note, std::lerp doesn't have any sort of thread locking problems. And a properly made lerp algorithm shouldn't either. It comes down to a few things:

1. Bus bandwidth: We have to spam the motors in order to get them to lerp the way we want. This means we spend a lot of time communicating on the CANBUS. This time could produce a latency when communicating with all of the servos. This latency would result in the movement of the steering servos and drive motors being out of sync and thus create wasteful and possible problematic forces on themselves and the structure of the robot as well as making piloting the rover difficult.
2. Confusing the device: Depending on how often you update the servo, this could cause erratic behavior with each update in position or speed.

We have done std::lerp successfully when controlling motors using motor controllers that we control directly via PWM that can handle such fast refresh rates. But if the servo already has this capability then there is no need to reinvent the wheel.
